### ISSUE TITLE
Runaway loop when playing Excessive Overkill

### ISSUE THREAD

**Issue by PhasecoreX** [scottadkin/node-utstats-2#15]
It seems that when playing any of the Excessive Overkill gametypes, this happens:
```
NodeUTStatsMutator AS-ColderSteel.NodeUTStatsMutator0 (Function NodeUTStats2.NodeUTStatsMutator.checkPlayerHWID:0056) Runaway loop detected (over 10000000 iterations)
```
The `checkPlayerHWID` part will change sometimes, but it's always one of the methods that `ModifyPlayer()` calls. It seems that for some reason, `ModifyPlayer()` gets called several thousand times on each spawn. So, for the first time a player is logged, you get this:
```
15.37	nstats	spawn_loc	0	0
15.37	nstats	Face	0	BossSkins.boss5Xan
15.37	nstats	Voice	0	Botpack.VoiceBoss
15.37	nstats	spawn_loc	0	0
15.37	nstats	spawn_loc	0	0
15.37	nstats	spawn_loc	0	0
15.37	nstats	spawn_loc	0	0
```
That line keeps repeating ~3070 times. Curiously, when I ran the mutator as a mutator (NodeUTStats2.NodeUTStatsMutator) instead of a ServerActor, this does not happen.

I've tried removing all of the contents of `ModifyPlayer()` besides the `if (NextMutator != None)` part and a log statement, still happens. I've tried many other gametypes and removed all of my other mutators, then it doesn't happen. It's just Excessive Overkill, and when run as a ServerActor. I am not sure why.

(Fixed upload for my comment below)
[Excessive2CF.zip](https://github.com/scottadkin/node-utstats-2/files/11142673/Excessive2CF.zip)

**Comment by scottadkin** [comment]
Can you send me a link for Excessive Overkill please?

**Comment by scottadkin** [comment]
I think I found the cause of it, I think it's a bug with Excessive calling Super.ModifyPlayer() in the weapon replacement mutator, just need to double check with others to see if my hunch is right.

**Comment by scottadkin** [comment]
Try this Excessive version with the unnecessary Super.ModifyPlayer() Removed [Excessive2CF.zip](https://github.com/scottadkin/node-utstats-2/files/11139003/Excessive2CF.zip)

I also removed Node Utstats 2 from my test server, and it still crashed with the 2.0 you provided.

**Comment by PhasecoreX** [comment]
Thank you! Didn't mean to sign you up to fix a really old gametype haha.

I think because you changed some classes from "Excessive2" to "Excessive2CF" but didn't update their references in the gametypes, none of the weapons actually worked. I updated them and fixed some other warnings and stuff. Also saw that `Super.ModifyPlayer(Other);` should be used, so updated to use that as well.

[Excessive2CF.zip](https://github.com/scottadkin/node-utstats-2/files/11142673/Excessive2CF.zip)

This one works correctly and doesn't spam the logs! Thank you for your help again!
