### ISSUE TITLE
winrate record wrong calculation

### ISSUE THREAD

**Issue by c0br3tii** [scottadkin/node-utstats-2#22]
Hi, if we go to records and list the players by winrates I get a lot of winrates above 100%....
But if then I click the players the winrate on its page looks correct...
![image](https://github.com/scottadkin/node-utstats-2/assets/103686485/eb420e8b-38c6-4230-a736-8522178e206e)
![image](https://github.com/scottadkin/node-utstats-2/assets/103686485/6857066d-5586-42b9-a712-55ac1ddc76f5)

**Comment by scottadkin** [comment]
What version is that? I remember I messed up the win rate but can't remember if I fixed it yet.

**Comment by scottadkin** [comment]
Ok wasn't what I originally thought but it's fixed for next release, what it was, was the recalculate player totals function that is called when using **node upgrade** I stupidly calculated the win rate as **wins / losses** instead of **wins / matches**.

**Comment by c0br3tii** [comment]
no problem... the player page is correct... its just the rankings that are off...

also, I ran the node upgrade twice... does that mess up my stats? It does not look like it... but just to confirm.

**Comment by scottadkin** [comment]
No it shouldn't, I made the upgrade script check for missing columns and such and it only alters tables if they do not exist, a while back it didn't and caused issues with duplicate settings for pages and such. The player total data is remade with the match data so it should be the same every time.

**Comment by c0br3tii** [comment]
cool. thanks!
