### ISSUE TITLE
help importing old logs

### ISSUE THREAD

**Issue by c0br3tii** [scottadkin/node-utstats-2#23]
Hi again!

I have a bunch of old logs previously imported by my old php stats page... when I try to import those logs, your imported says:

[35m[00:05:43] Progress: Starting import of log number 1 of 11[0m
[36m[00:05:43] Notice: Starting import of log file Unreal.ngLog.2023.06.03.19.33.34.7777.log[0m
[36m[00:05:43] Notice: Auto merge players by HWID is set to false[0m
[36m[00:05:43] Notice: There is no match realstart event, skipping import.[0m
[33m[00:05:43] Warning: Importer.updateCurrentUpdatedStats() currentData is undefined[0m

when I look at the logs, information seems to be there, but I believe the spaces between characters was removed by the old page before creating backups...
![image](https://github.com/scottadkin/node-utstats-2/assets/103686485/be89ccf4-7563-4175-a4ca-7fd573d03faf)

Any idea what I can do to import those old logs?

Thanks!

**Comment by scottadkin** [comment]
The spaces are null characters(doesn't matter if they are present or not), old logs should import fine though, it could be encoding related try looking at the files encoding(may need to add another check to convert files if needed), the only other thing that I can think of is the log doesn't have this line **XXXX.XX	game	realstart**, I added that check to stop empty logs(or matches that only had warmup before a map switch) being imported.

**Comment by c0br3tii** [comment]
it does have that... I'm attaching an example if you can quickly have a look...
[Unreal.ngLog.2023.05.19.02.21.18.7777.log](https://github.com/scottadkin/node-utstats-2/files/11648150/Unreal.ngLog.2023.05.19.02.21.18.7777.log)

Hope you don't need to spend long!

thank you in advance...

**Comment by c0br3tii** [comment]
I think I found the issue... the logs pre-processed don't have the lines with 'netstat...'....
You importer must use those lines and then it does not work.
:(

**Comment by scottadkin** [comment]
I removed the log you uploaded because it has HWID's, and IPs in it, looking into the issue though.

**Comment by scottadkin** [comment]
Here is a test fix, replace the files with these ones, you will also have to run **npm install** as there is a new package used to check the file encoding and converts the file data if needed.
[Importer test fix.zip](https://github.com/scottadkin/node-utstats-2/files/11654190/Importer.test.fix.zip)

**Comment by c0br3tii** [comment]
Cool, will try as soon as I get back home. West coast Canada here btw.
Thanks!

**Comment by c0br3tii** [comment]
IT WORKS!!!
![image](https://github.com/scottadkin/node-utstats-2/assets/103686485/73afe36f-5a4c-4d8c-ae4a-b79efccdccc8)

will leave it busy overnight!!!...
I hope that, if the time processing the logs is longer than the time for the logger to check again, it won't be a problem lolol
Thank you so much!

**Comment by scottadkin** [comment]
The importer checks if the previous import attempt is still running, if it is it skips the current import interval until the first import has finished.

**Comment by c0br3tii** [comment]
cool... One other thing, can I duplicate my install folder to run a second importer on a different machine to same database?
does the database allow to have two importers running at same time.

**Comment by scottadkin** [comment]
I have not tested that at all tbh, probably would be a good idea in the future to add the option of running multiple importers concurrently.

**Comment by c0br3tii** [comment]
Its ok... It looks like the limiting factor might be the database machine
anyways....

**Comment by c0br3tii** [comment]
Also, would you be concerned if the database gets too big? I do have a lot
of logs...

**Comment by c0br3tii** [comment]
Awesome, thank you so much!

**Comment by c0br3tii** [comment]
one non related issue... 
somehow I have two players that have same HWID from ACE... its true.. I dont know how... for that I cannot import using ace...
do you have any idea how one of them can change his HWID?

thanks
