### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by oskrtg** [scottadkin/node-utstats-2#7]
api/user.js on line 5:
const salt = require ('../salt');

There is no salt file in the indicated directory: resulting in Module not found: Can't resolve '../salt'

Missing a file on check in or dependency missing in package.json

**Comment by scottadkin** [comment]
That file is created when you run **node install** after running **npm install**.

**Comment by oskrtg** [comment]
Apologies, I made a simple oversight. All working now. 
The issue was caused by running a newer version >5.6 of mysql: you need to specify legacy password use for the install to be able to complete. Because the install did not complete the file was not being created.
more info here: [Node.js not connecting to mysql](https://stackoverflow.com/questions/44946270/er-not-supported-auth-mode-mysql-server)
