### ISSUE TITLE
Classic mode has incompatibility with mysql 8+

### ISSUE THREAD

**Issue by oskrtg** [scottadkin/node-utstats-2#8]
As per this [mysql documentation page](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-R)

The keyword 'RANK' has been added and reserved - this causes some issues with queries where rank is called as a column name without proper back ticking.

Suggested fix is to change queries by including backticked column names EX: 
const query = "SELECT \`time\`,\`pid\`,\`rank\`,\`prevrank\`,\`matches\` FROM \`uts_rank\` WHERE \`gid\`=? ORDER BY \`rank\` DESC LIMIT ?, ?";

The written queries will function correctly on mysql < 8, but given the usage of the reserved keywork RANK in the column space, an identifier backtick must be used.

**Comment by scottadkin** [comment]
I've been meaning to remove the classic mode, I have not touched the code for probably nearly 2 years, and I've not tested it at all for nearly that long as well.
